<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38679" started-at="2019-12-07T04:26:48Z" finished-at="2019-12-07T04:27:26Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="38679" started-at="2019-12-07T04:26:48Z" finished-at="2019-12-07T04:27:26Z">
      <class name="com.qa.test.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.test.HomePageTest@80ec60]" name="setup" is-config="true" duration-ms="9606" started-at="2019-12-07T09:56:48Z" finished-at="2019-12-07T09:56:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="checkwarningmsg()[pri:8, instance:com.qa.test.HomePageTest@80ec60]" name="checkwarningmsg" duration-ms="9634" started-at="2019-12-07T09:56:58Z" finished-at="2019-12-07T09:57:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [If you want to be able to fully use the AdminModules panel and have free modules available, you should enable the following configuration on your server
- Enable PHP's allow_url_fopen setting] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [If you want to be able to fully use the AdminModules panel and have free modules available, you should enable the following configuration on your server
- Enable PHP's allow_url_fopen setting] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.qa.test.HomePageTest.checkwarningmsg(HomePageTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkwarningmsg -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.qa.test.HomePageTest@80ec60]" name="teardown" is-config="true" duration-ms="741" started-at="2019-12-07T09:57:08Z" finished-at="2019-12-07T09:57:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkwarningmsg status=FAILURE method=HomePageTest.checkwarningmsg()[pri:8, instance:com.qa.test.HomePageTest@80ec60] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.test.HomePageTest@80ec60]" name="setup" is-config="true" duration-ms="9773" started-at="2019-12-07T09:57:09Z" finished-at="2019-12-07T09:57:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="checkmrktplctitle()[pri:9, instance:com.qa.test.HomePageTest@80ec60]" name="checkmrktplctitle" duration-ms="5993" started-at="2019-12-07T09:57:19Z" finished-at="2019-12-07T09:57:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [exp] but found [Dashboard • SHOPCART]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [exp] but found [Dashboard • SHOPCART]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.qa.test.HomePageTest.checkmrktplctitle(HomePageTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkmrktplctitle -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.qa.test.HomePageTest@80ec60]" name="teardown" is-config="true" duration-ms="652" started-at="2019-12-07T09:57:26Z" finished-at="2019-12-07T09:57:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkmrktplctitle status=FAILURE method=HomePageTest.checkmrktplctitle()[pri:9, instance:com.qa.test.HomePageTest@80ec60] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.qa.test.HomePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
